### ISSUE TITLE
Messy conversion 

### ISSUE THREAD

**Issue by mbConlon** [KenwoodFox/SNUB#4]
Brackets and paranthesis remain when converting to list.
![bugReport](https://user-images.githubusercontent.com/125571404/223790084-bc276851-58fb-4842-8da2-0021eb596be6.PNG)

**Comment by KenwoodFox** [comment]
Since we fixed the earlier bug where the combobox `.Add()` would stringify the type, can we try going back to the casting method?

```c#
list req = arr.ToObject<List<string>>();
```

?
